apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-account
  labels:
    app: the-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-account
  template:
    metadata:
      labels:
        app: the-account
    spec:
      containers:
        - name: the-account
          image: registry.digitalocean.com/vortex-studio/the-account:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: MONGODB_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: mongodb-connection-secret
                  key: MONGODB_URI
            - name: MENU_ANALYZER_URL
              value: http://menu-analyzer-service:8000/analyze-menu
            - name: KEYCLOAK_URL
              value: https://keycloak.vortex.studio/auth
            - name: KEYCLOAK_CLIENT_ID
              value: the-account
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret
                  key: KEYCLOAK_CLIENT_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key-secret
                  key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: the-account-service
spec:
  selector:
    app: the-account
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP
