apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-credentials
  namespace: keycloak
type: Opaque
data:
  POSTGRES_USER: a2V5Y2xvYWs=  # Base64 for "keycloak"
  POSTGRES_PASSWORD: bXlzZWN1cmVwYXNzd29yZA==  # Base64 for "mysecurepassword"
  POSTGRES_DB: a2V5Y2xvYWs=  # Base64 for "keycloak"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret
type: Opaque
data:
  KEYCLOAK_CLIENT_SECRET: Z2V0LWNsaWVudC1zZWNyZXQtZnJvbS1jbHVzdGVy